[package]
name = "radar_monitor"
version = "1.0.0"
authors = ["Niklas Larsson <niklaslarsson95@gmail.com>"]

[dependencies]
ftp = "*"
image = "*"
vulkano = "*"
vulkano-shader-derive = "*"
vulkano-win = "*"
winit = "*"
