[package]
name = "radar_monitor"
version = "1.0.0"
authors = ["Niklas Larsson <niklaslarsson95@gmail.com>"]

[dependencies]
ftp = "*"
glium = "*"
image = "*"
firebase = { git = "https://github.com/Phrohdoh/firebase-rs.git" }
